dataset:
  folder: "data/gnn_dyn_data_custom" # gen_data
  init_pos: 'spread'
  # initialization options:
  # - 'spread': deterministic spreaded object pile
  # - 'rand_blob': random blob-shape object pile
  # - 'rand_spread': random spreaded object pile
  # - 'rand_sparse_spread': random sparse spreaded object pile
  global_scale: 24
  n_episode: 2000
  n_timestep: 10
  obj: "carrots"
  particle_r: 0.125
  cam_idx: 0
  wkspc_w: 5.0
  headless: True
  cont_motion: False
  robot_type: 'franka' # kinova; franka

train:
  data_root: "data/gnn_dyn_data"
  random_seed: 42
  n_epoch: 2000
  lr: 0.001
  adam_beta1: 0.9
  batch_size: 4
  nf_hidden: 64
  num_workers: 5
  train_valid_ratio: 0.9
  log_per_iter: 50
  ckp_per_iter: 1000
  resume_epoch: -1
  resume_iter: -1
  n_history: 1
  n_rollout: 5
  rollout_decay: 1.0
  lr_scheduler:
    type: "StepLR"
    enabled: True
    step_size: 1000 # epochs
    gamma: 0.1 # reduce LR by this factor
    factor: 0.1 # ReduceLROnPlateau
    patience: 10 # ReduceLROnPlateau
    threshold_mode: 'rel' # ReduceLROnPlateau
    cooldown: 0 # ReduceLROnPlateau
  particle:
    nf_effect: 64
    resume:
      active: False
      epoch: 0
      iter: 0
      folder: 'None'
    adj_thresh: 0.08
    add_delta: False
  lam_reg: 2e-4
  lam_sp: 1e-2
